//Get Requests
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_FAILURE = "PRODUCTS_FAILURE";

//Post Requests
export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

//Delete Requests
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

//Patch Requests
export const CHANGE_PRODUCT_REQUEST = "CHANGE_PRODUCT_REQUEST";
export const CHANGE_PRODUCT_SUCCESS = "CHANGE_PRODUCT_SUCCESS";
export const CHANGE_PRODUCT_FAILURE = "CHANGE_PRODUCT_FAILURE";
